### ISSUE TITLE
add out-of-workflow e-mail endpoints

### ISSUE THREAD

**Issue by bwolkerstorfer** [eRecruiter/eRecruiter.Api#23]
In some cases - third-party portal developers - it is required that an registration or application confirmation is being sent later in the process which is currently not possible. The current logic only allows to send confirmation e-mails within the the workflow process.

The enhancement should allow the API developers to send a confirmation e-mail when they are required to send it at any time later.

**Comment by afuersch** [comment]
#25 successfully merged.
